export const POST_DATA_BOX = 'POST_DATA_BOX'
export const FACE_PATTERN_DATA_BOX = 'FACE_PATTERN_DATA_BOX'
export const STEATE_DATA_BOX = 'STEATE_DATA_BOX'

export const POST_DATA_CATEGORY = 'POST_DATA_CATEGORY'
export const FACE_DATA_CATEGORY = 'FACE_DATA_CATEGORY'
export const ENDED_DATA_CATEGORY = 'ENDED_DATA_CATEGORY'
export const POST_ITEM_DATA_BOX = 'POST_ITEM_DATA_BOX'

export const SET_LOADING = 'SET_LOADING'
